### ISSUE TITLE
Un cas particulier de “给”

### ISSUE THREAD

**Issue by CourantenCourant** [pmagistry/test_arborator#25]
“给” est souvent un comp:obl comme dans "我晚上要给妈妈打电话。" Cependant, dans :

196 沙 發 被 小 孩 給 踏 壞 了 。 

Je ne vois pas la relation entre 给 et 踩坏.

**Comment by CourantenCourant** [comment]
C'est un emploi particulier de 给 où il est modifieur de 踏坏. Donc il fonctionne comme un adverbe.

**Comment by pmagistry** [comment]
TODO pour moi: retrouver l'article de MC Paris
