### ISSUE TITLE
Complément d'objet dans la construction "他幫別人照顧小孩"

### ISSUE THREAD

**Issue by CourantenCourant** [pmagistry/test_arborator#3]
12 他 幫 別 人 照 顧 小 孩 。

https://github.com/pmagistry/test_arborator/blob/decbfd5b264cddd258e88964ffb2bb9bf7fa3800/charbased.conllu#L126

Dans "他帮别人照顾小孩", il faut spécifier quelle est la relation entre les deux verbes.

Ce n'est pas possible qu'il y a deux compléments d'objet pour le verbe "帮"。

**Comment by pmagistry** [comment]
il faut mieux mettre 幫 -[comp:svc]-> 照顧

**Comment by pmagistry** [comment]
préferer -[compound:svc]->
(cf. https://guidelines.surfacesyntacticud.org/docs/language/mandarin_chinese/syntaxic/serial_verbs_construction/ )
