### ISSUE TITLE
Un verbe peut-il avoir deux comp:obj ?

### ISSUE THREAD

**Issue by CourantenCourant** [pmagistry/test_arborator#42]
charbased__414 讓 他 多 休 息 。 

Il paraît que 让 a deux comp:obj, 他 et 休息.

**Comment by ilaine** [comment]
Si je me souviens bien, cet issue a été résolu jeudi dernier ?

Ca donnait : 

- laisser - comp:obj -> 他
- laisser - comp:pred -> 休息 ?

Mais pour répondre à la question de façon générale, j'ai l'impression que souvent on a quand même plutôt un seul `comp:obj` et le second est soit `comp:obl` soit `comp:pred`.

Si l'issue est bien résolu, je vous laisse le soin de le fermer !

**Comment by CourantEnCourant** [comment]
Oui j'avais oublié de fermer cette issue.
