### ISSUE TITLE
"我们两个", mod ou appos ?

### ISSUE THREAD

**Issue by CourantenCourant** [pmagistry/test_arborator#8]
30 我 們 兩 個 錯 身 而 過 ， 沒 有 遇 到 。36 他 們 兩 個 人 平 常 最 喜 歡 鬥 嘴 。

Entre "他们" et "两个", c'est un mod ou un conj:appos ? (je pense que plutôt conj:appos)

**Comment by zung6git6** [comment]
J'ai la même question sur des constructions similaires comme : 
sent_id 256 : **我 們 這 個** 月 的 生 產 目 標 要 比 上 個 月 的 數 量 加 倍 。
sent_id 375 : 算 命 先 生 說 **他 們 兩 人** 的 八 字 不 合 。

**Comment by pmagistry** [comment]
我們-->兩個 ： plutôt mod vs. 我們兩個人 plutôt appos (discuter conj:appos vs. appos)
