### ISSUE TITLE
Annotation des clivées

### ISSUE THREAD

**Issue by CourantenCourant** [pmagistry/test_arborator#9]
44 自 由 的 生 活 是 人 人 都 想 要 過 的 。

Je pense qu'il s'agit d'une clivée, et cette structure est absente dans guidelines. J'ai un peu de mal à la comprendre, l'annoter et la chercher dans grewmatch.

On peut prendre cette phrase comme référence pour écrire un guide pour les clivées.

**Comment by pmagistry** [comment]
d'accord

**Comment by zung6git6** [comment]
有的...
une relation de comp:cleft, qui part de 有 à son dépendant, relation mod de 有 à 的
